// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4wWDNeTjgpKl3PoZl6uQyClsGvZ_fjA',
    appId: '1:196250959619:web:239cb0895f100d59ba3336',
    messagingSenderId: '196250959619',
    projectId: 'practo-doctor-test',
    authDomain: 'practo-doctor-test.firebaseapp.com',
    storageBucket: 'practo-doctor-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8z5ISelYPWmtoH8p8tGqrzA9v9mx5Ug',
    appId: '1:196250959619:android:f418fc034a84206bba3336',
    messagingSenderId: '196250959619',
    projectId: 'practo-doctor-test',
    storageBucket: 'practo-doctor-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZmQ3ZqDuWx1TbvIIpRAnx1qVAI5PpVB0',
    appId: '1:196250959619:ios:3967ff1d244ffc0eba3336',
    messagingSenderId: '196250959619',
    projectId: 'practo-doctor-test',
    storageBucket: 'practo-doctor-test.appspot.com',
    iosBundleId: 'com.example.practoDoctorTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZmQ3ZqDuWx1TbvIIpRAnx1qVAI5PpVB0',
    appId: '1:196250959619:ios:7dab93904e1fd9f4ba3336',
    messagingSenderId: '196250959619',
    projectId: 'practo-doctor-test',
    storageBucket: 'practo-doctor-test.appspot.com',
    iosBundleId: 'com.example.practoDoctorTest.RunnerTests',
  );
}
